<a href="https://colab.research.google.com/github/jacksonguedes/Introdu-o_Ciencia_Dados/blob/main/Introdu%C3%A7%C3%A3o_%C3%A0_Ci%C3%AAncia_de_Dados01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Demonstração  NumPy  
Disciplina - Introdução à Ciência de Dados - Univesp  
Prof. Dr. José Eduardo Santarem Segundo

Importando biblioteca

In [1]:
import numpy as np

Gerando um NDArray de 2x3

In [2]:
dados = np.random.rand(2,3)
dados

array([[0.10684123, 0.45302373, 0.54264681],
       [0.63713592, 0.99286919, 0.04644709]])

Tipo de dado

In [3]:
dados.dtype

dtype('float64')

Tamanho dodado

In [4]:
dados.shape

(2, 3)

In [5]:
dados.ndim # 2 dimensões

2

Outras maneiras de criar arrays

In [7]:
dadoszeros = np.zeros(10)
dadoszeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
dadoszeros = np.zeros((3,10))
dadoszeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
dadosum = np.ones(10)
dadosum

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
dadosseq = np.arange(0, 11, 2)
dadosseq

array([ 0,  2,  4,  6,  8, 10])

Mudança do tipo de dado

In [14]:
dadosseqf = dadosseq.astype(np.float64)
dadosseqf

array([ 0.,  2.,  4.,  6.,  8., 10.])

Aritmética com arrays

In [16]:
dados = np.array([[1, 2, 3], [4, 5, 6]])
dados

array([[1, 2, 3],
       [4, 5, 6]])

Multiplicação

In [17]:
dados * dados

array([[ 1,  4,  9],
       [16, 25, 36]])

Divisão

In [18]:
1 / dados

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

Subtração

In [20]:
dados - dados

array([[0, 0, 0],
       [0, 0, 0]])

Soma

In [21]:
dados + dados

array([[ 2,  4,  6],
       [ 8, 10, 12]])


Gerando um novo array

In [24]:
dados1 = dados * dados
dados1

array([[ 1,  4,  9],
       [16, 25, 36]])

Comparando os arrays

In [25]:
dados1 > dados

array([[False,  True,  True],
       [ True,  True,  True]])

Array com mais de uma dimensão

In [26]:
dados2 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
dados2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
dados2[2, 1]

8

Máscaras

In [29]:
mascara = (dadosseq > 5)
mascara

array([False, False, False,  True,  True,  True])

In [31]:
dadosseq[dadosseq>9] = 999
dadosseq

array([  0,   2,   4,   6,   8, 999])

Transposição

In [32]:
dados3 = np.arange(15).reshape((3,5))
dados3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
dados3.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Multiplicação de matrizes

In [34]:
np.dot(dados3.T, dados3)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])